<?php
$title = 'Add new place';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$place = $form->get('place');
$place->setAttribute('class', 'form-control');
$place->setAttribute('placeholder', 'Place');

$brand = $form->get('brand');
$brand->setAttribute('class', 'form-control');
$brand->setAttribute('placeholder', 'Brand');

$model = $form->get('model');
$model->setAttribute('class', 'form-control');
$model->setAttribute('placeholder', 'Model');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('cashregister', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php ?>
    <div class="form-group">
        <?= $this->formLabel($place) ?>
        <?= $this->formElement($place) ?>
        <?= $this->formElementErrors()->render($place, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($brand) ?>
        <?= $this->formElement($brand) ?>
        <?= $this->formElementErrors()->render($brand, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($model) ?>
        <?= $this->formElement($model) ?>
        <?= $this->formElementErrors()->render($model, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();